### ISSUE TITLE
draft-js-link-plugin warning (Unknown prop contentState)

### ISSUE THREAD

**Issue by po5i** [ld-x/last-draft-js-plugins#4]
I have a similar issue like this https://github.com/draft-js-plugins/draft-js-plugins/issues/398 but it says

> Warning: Unknown prop `contentState` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
>            in a (created by Link)

**Comment by po5i** [comment]
Also will be useful to update linkStrategy.js because `Entity.get()` will be deprecated on next React version

**Comment by scf4** [comment]
Having the same issue
